language: python
python:
  - 2.7
install:
  - pip install -e .
  - pip install coverage pep8
script:
  - nosetests --with-coverage --cover-package=flask_blogging --cover-min-percentage=85 -v
  - pep8 --repeat flask_blogging/ test/
notifications:
  email: false